### ISSUE TITLE
Add option to Stripe Payment Settings to allow changing what's sent to Stripe for the Name field when billing details are not captured

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/eea-stripe-gateway#4]
Codebase https://events.codebasehq.com/projects/event-espresso/tickets/10086

Per @joshfeck 

Requested here:

https://eventespresso.com/topic/registrant-details-not-forwarded-to-skype-or-passed-on-incorrectly

One way to make this happen is add an option (or even a filter hook would be fine, really) so that the Name value in the payment transaction on Stripe's end is not the email address from the reg form, but instead, is a combination of the first and last name of the primary registrant.

requested again:

https://eventespresso.com/topic/specify-which-registrants-email-is-passed-to-stripe/

**Comment by mnelson4** [comment]
hmmm I scanned over the code and am not sure why the "name" is the customer's email. I'll need to look over Stripe's documentation more.
@knazart do you have any suggestions on this one?

**Comment by knazart** [comment]
>Name: (which is actually an email not a name)

The `name` field that is being sent to Stripe is "The name of your company or website", and it can appear as an email only if the organization name value in EE settings is an email. On the other hand, I would assume that if the billing info is not being collected by Stripe then maybe they just save email as the Name.
Surfing through the DOCs I don't quite see an option to pass the billing info into the the Stripe pop-up. But now you can make Stripe send receipts to clients with a `receipt_email` parameter in the creation of the charge.

**Comment by mnelson4** [comment]
Thanks for the investigation @knazart. Ya I just tested and see if no billing info is entered into the Stripe pop-up, ya it's definetely the registrant's email being put into the "name" field (not the site owner's email). eg https://drive.google.com/a/eventespresso.com/file/d/1LHABcFOLOXaSdwtOK6lnuM-hyipr82Xs/view?usp=drivesdk
Still investigating...

**Comment by mnelson4** [comment]
For the record, here's the applicable Stripe documentation: https://stripe.com/docs/checkout

**Comment by mnelson4** [comment]
Related discussion on wpmu: https://premium.wpmudev.org/forums/topic/setup-name-on-card-and-billing-address-for-stripe-paymentsubscription-in-membership-pro, although the "solution" seems to be to just require billing data.

**Comment by mnelson4** [comment]
I'm sorry @joshfeck I don't see a way to change the "name" on the card to anything other than their email when no billing info is provided. I also looked into using the Stripe REST API to update the card but that doesn't seem to work either. (See https://stripe.com/docs/api#retrieve_source, which should be how we'd bring up the card info, but I can't retrieve a card that doesn't have an associated customer created, and customers are only created when billing data is requested. Eg payment `ch_DLpwzySaVq2Lgp` says there is an associated customer, https://drive.google.com/a/eventespresso.com/file/d/1R5SFTxBrmy5f8kYsLRNN6T5E1CPEJCLH/view?usp=drivesdk, and shows their email, but no such customer actually exists in the web UI, nor in the REST API: https://drive.google.com/file/d/1fXqLJGFtQCQJXoSfkx7FQ5uoae_owCfn/view ).

I think the best we can do is change the description (see https://drive.google.com/file/d/1fXqLJGFtQCQJXoSfkx7FQ5uoae_owCfn/view) to be a dump of the event name, ticket name, registrant name, etc. Whereas right now it's just the event name.

Specifically, I'd suggest the description could become: 

> Event Registration. Website: {site_url} Event: {event_name} Ticket {ticket-name}({ticket-id}) Registration {attendee-full-name} ({registration-code})

eg

Event Registraiton. Website: mysite.com, Event: House Party, Ticket: General Admission (13), Registration: Mike Nelson (g4g44g2-4g35)

Thoughts?

**Comment by mnelson4** [comment]
oh and we'd make that filterable

**Comment by mnelson4** [comment]
> Then when I check the payment log, I can see that the primary reg's email address is passed to the name field... Can there be a way to send the Primary Registrant's name to that field?

It's not clear from those logs, but that's actually a RESPONSE sent from Stripe. We didn't send that `name` field. Stripe's API only permits us to send the email ahead of time, and they use that for the "name". I looked over https://stripe.com/docs/checkout#integration-custom and I can't see a way to change that.

I think if we want to pass the customer's info to Stripe, we need to:

* create a customer in Stripe
* update the card on it

iirc we were creating customers in Stripe at one point, but disabled that for some reason. @knazart or @joshfeck do you remember if that was correct and what, if any, problems there were with that?

> So in addition to the above, can there be a way to send the Primary reg's email address to the receipt_email field?

Yeah, that's easy. I think I'll do that in a separate PR because it's relatively so straightforward.

**Comment by mnelson4** [comment]
Here's some relevant documentation:
* Stripe's JS can either pass us a token or a source: https://stripe.com/docs/checkout#integration-custom (and on https://stackoverflow.com/questions/50284633/stripe-payments-source-vs-token-card someone explains that tokens are meant to be single-use, whereas sources are meant to be reusable)
* how to create a customer and attach a source (eg the card data paypal's JS created for us): https://stripe.com/docs/sources/customers#attaching-a-source-to-a-new-customer-object
* how to update a card's name: https://stripe.com/docs/api/php#update_card

**Comment by knazart** [comment]
I don't really remember how it was before Mike and if we were creating customers ourselves at all. I don't remember removing that. Right now, it seems like we just create the payment through their API but using an SDK and that might also be an issue because it's most likely now outdated. I'd say we should consider dropping the SDK if possible and just building direct requests to their API.

Btw, Mike, do you want me to review #6 ? Is it ready ? You didn't assign a reviewer.

**Comment by mnelson4** [comment]
Kk thanks @knazart. 

> I'd say we should consider dropping the SDK if possible and just building on direct requests to their API.

Ya maybe, although they do have code samples that use their PHP SDK there still (eg https://stripe.com/docs/api/php#update_card shows a code sample using PHP, but the default is to show the REST API code sample). So it's not like they've deprecated the PHP SDK.

You're right though, that the Stripe PHP SDK we're using is really out of date. Apparently we're on version 1.16, whereas the latest release from https://github.com/stripe/stripe-php/releases is 6.15! 6.15 requires PHP 5.4 which we do too, so we could try upgrading. 

Personally I'm inclined to not refactor everything to use the REST API directly (because we'd basically end up building our own SDK), and instead handle updating the PHP SDK on a separate ticket.

**Comment by mnelson4** [comment]
chatted with "stripe support" to see if the "customer" column in the Stripe dashboard (https://drive.google.com/a/eventespresso.com/file/d/1SttGnDohy8hzdXmsGDuiEYMjm5hxQb6T/view?usp=drivesdk) can be customized. They said it couldn't, but they also said they weren't a developer (I suspect they weren't human either :robot: ).
I hopped onto #stripe channel on freenode IRC and asked about it, we'll see if I get a response...
I've also e-mailed their support.
But right now, it seems:
1. The "customer" column in the Stripe dashboard will always be the user's email (that's what "Stripe support" said, and I can't find any way around that; plus, even when Stripe Checkout does request the user's billing info, it still only shows their email)
2. The "owner" area of Stripe's payment details page (see https://drive.google.com/a/eventespresso.com/file/d/1EZFhBpSCdTiaioHOdlc9KFwE_Ej0fC7C/view?usp=drivesdk) isn't modifiable either. Or it could be but I can't figure out how to change that with Stripe Checkout without requesting billing info.

I still think the best we can do is change the event description (I know, same as I suggested earlier: https://github.com/eventespresso/eea-stripe-gateway/issues/4#issuecomment-410393611)

**Comment by Pebblo** [comment]
Here's a filter for setting receipt_email on the fly:

https://github.com/eventespresso/ee-code-snippet-library/blob/master/payment-methods/tw_ee_stripe_data_array.php

There was talk a while back about adding this an as an option in the Stripe settings (because its ANOTHER email... oh my!) as some users may not want it.

---

With regards to this - https://drive.google.com/file/d/1t5o9V0oBWz862nYjSTfEIcDYy-_ra-BS/view
I think we can get 'better' reporting there if we actually create 'Customers' and within Stripe, then charge the customer.... not just create a charge linked to an email.

**Comment by mnelson4** [comment]
> Here's a filter for setting receipt_email on the fly:

> eventespresso/ee-code-snippet-library:payment-methods/tw_ee_stripe_data_array.php@master

> There was talk a while back about adding this an as an option in the Stripe settings (because its ANOTHER email... oh my!) as some users may not want it.

Right, that was also recently addressed on https://github.com/eventespresso/eea-stripe-gateway/pull/6. So we're sending the `receipt_email` now.

> With regards to this - drive.google.com/file/d/1t5o9V0oBWz862nYjSTfEIcDYy-_ra-BS/view
I think we can get 'better' reporting there if we actually create 'Customers' and within Stripe, then charge the customer.... not just create a charge linked to an email.

Ok so I'll take that as a vote in favour of https://github.com/eventespresso/eea-stripe-gateway/pull/7, right?

**Comment by mnelson4** [comment]
I'm ok with reverting #6 (not released yet anyway), and just closing #7 if those features will actually more generally be seen as a problem than a feature.

I'm also open to adding admin options to 

1. Have stripe send a receipt email (defaulting to sending to the primary registrant; although that will be filterable if someone wants to instead send it to the purchaser; basically #6)
2. Create a customer in Stripe based on billing info (defaulting to the primary registrant, but again we'd make sure there were filters so it can instead be sent to the "purchaser"; so this would mostly be #7)

but that will be more code to maintain and possibly have bugs, so we should probably only do that if you're confident some people will actually want to that.

And again, if we're seeing #6 and #7 will add more problems than they solve, I'm in favour of just closing them for now. Thoughts @Pebblo @joshfeck ?

**Comment by joshfeck** [comment]
Let's revert #6 since it's not requested that often, and anyone that does request can use a filter hook to do it. This (and #7) can be closed for now. I'm sorry for the trouble.

**Comment by Pebblo** [comment]
Reverting #6 was done in #9  and #7 is already closed

So I'll now close this.
